/**
 * ============================================================================
 * Ascend Enterprise UI
 * PhoneField
 * ----------------------------------------------------------------------------
 * File: africa.ts
 *
 * Africa country dataset.
 *
 * Part 1
 * - North Africa
 * - East Africa
 *
 * ============================================================================
 */

import type {
    PhoneCountry,
} from "../PhoneField.types";

/* -------------------------------------------------------------------------- */
/* Africa                                                                     */
/* -------------------------------------------------------------------------- */

export const AFRICAN_COUNTRIES: readonly PhoneCountry[] = [

    /* ====================================================================== */
    /* North Africa                                                           */
    /* ====================================================================== */

    {
        code: "DZ",
        alpha3: "DZA",
        numericCode: "012",
        name: "Algeria",
        englishName: "Algeria",
        dialCode: "+213",
        flag: "🇩🇿",
        region: "Africa",
        subregion: "Northern Africa",
        example: "551 23 45 67",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "EG",
        alpha3: "EGY",
        numericCode: "818",
        name: "Egypt",
        englishName: "Egypt",
        dialCode: "+20",
        flag: "🇪🇬",
        region: "Africa",
        subregion: "Northern Africa",
        example: "100 123 4567",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "LY",
        alpha3: "LBY",
        numericCode: "434",
        name: "Libya",
        englishName: "Libya",
        dialCode: "+218",
        flag: "🇱🇾",
        region: "Africa",
        subregion: "Northern Africa",
        example: "91 234 5678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "MA",
        alpha3: "MAR",
        numericCode: "504",
        name: "Morocco",
        englishName: "Morocco",
        dialCode: "+212",
        flag: "🇲🇦",
        region: "Africa",
        subregion: "Northern Africa",
        example: "612 345 678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "SD",
        alpha3: "SDN",
        numericCode: "729",
        name: "Sudan",
        englishName: "Sudan",
        dialCode: "+249",
        flag: "🇸🇩",
        region: "Africa",
        subregion: "Northern Africa",
        example: "912 345 678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "TN",
        alpha3: "TUN",
        numericCode: "788",
        name: "Tunisia",
        englishName: "Tunisia",
        dialCode: "+216",
        flag: "🇹🇳",
        region: "Africa",
        subregion: "Northern Africa",
        example: "20 123 456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    /* ====================================================================== */
    /* East Africa                                                            */
    /* ====================================================================== */

    {
        code: "BI",
        alpha3: "BDI",
        numericCode: "108",
        name: "Burundi",
        englishName: "Burundi",
        dialCode: "+257",
        flag: "🇧🇮",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "79 12 34 56",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "KM",
        alpha3: "COM",
        numericCode: "174",
        name: "Comoros",
        englishName: "Comoros",
        dialCode: "+269",
        flag: "🇰🇲",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "321 23 45",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "DJ",
        alpha3: "DJI",
        numericCode: "262",
        name: "Djibouti",
        englishName: "Djibouti",
        dialCode: "+253",
        flag: "🇩🇯",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "77 12 34 56",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "ER",
        alpha3: "ERI",
        numericCode: "232",
        name: "Eritrea",
        englishName: "Eritrea",
        dialCode: "+291",
        flag: "🇪🇷",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "712 3456",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "ET",
        alpha3: "ETH",
        numericCode: "231",
        name: "Ethiopia",
        englishName: "Ethiopia",
        dialCode: "+251",
        flag: "🇪🇹",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "911 234 567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "KE",
        alpha3: "KEN",
        numericCode: "404",
        name: "Kenya",
        englishName: "Kenya",
        dialCode: "+254",
        flag: "🇰🇪",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "712 345 678",
        nationalNumberLength: 9,
        internationalPrefix: "000",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "MG",
        alpha3: "MDG",
        numericCode: "450",
        name: "Madagascar",
        englishName: "Madagascar",
        dialCode: "+261",
        flag: "🇲🇬",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "32 12 345 67",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "MU",
        alpha3: "MUS",
        numericCode: "480",
        name: "Mauritius",
        englishName: "Mauritius",
        dialCode: "+230",
        flag: "🇲🇺",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "5251 2345",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "MZ",
        alpha3: "MOZ",
        numericCode: "508",
        name: "Mozambique",
        englishName: "Mozambique",
        dialCode: "+258",
        flag: "🇲🇿",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "82 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "RW",
        alpha3: "RWA",
        numericCode: "646",
        name: "Rwanda",
        englishName: "Rwanda",
        dialCode: "+250",
        flag: "🇷🇼",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "788 123 456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "SC",
        alpha3: "SYC",
        numericCode: "690",
        name: "Seychelles",
        englishName: "Seychelles",
        dialCode: "+248",
        flag: "🇸🇨",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "251 2345",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "SO",
        alpha3: "SOM",
        numericCode: "706",
        name: "Somalia",
        englishName: "Somalia",
        dialCode: "+252",
        flag: "🇸🇴",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "61 2345678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "SS",
        alpha3: "SSD",
        numericCode: "728",
        name: "South Sudan",
        englishName: "South Sudan",
        dialCode: "+211",
        flag: "🇸🇸",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "977 123 456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "TZ",
        alpha3: "TZA",
        numericCode: "834",
        name: "Tanzania",
        englishName: "Tanzania",
        dialCode: "+255",
        flag: "🇹🇿",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "712 345 678",
        nationalNumberLength: 9,
        internationalPrefix: "000",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "UG",
        alpha3: "UGA",
        numericCode: "800",
        name: "Uganda",
        englishName: "Uganda",
        dialCode: "+256",
        flag: "🇺🇬",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "712 345678",
        nationalNumberLength: 9,
        internationalPrefix: "000",
        trunkPrefix: "0",
        independent: true,
    },

];
    /* ====================================================================== */
    /* Central Africa                                                         */
    /* ====================================================================== */

    {
        code: "AO",
        alpha3: "AGO",
        numericCode: "024",
        name: "Angola",
        englishName: "Angola",
        dialCode: "+244",
        flag: "🇦🇴",
        region: "Africa",
        subregion: "Middle Africa",
        example: "923 123 456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "CM",
        alpha3: "CMR",
        numericCode: "120",
        name: "Cameroon",
        englishName: "Cameroon",
        dialCode: "+237",
        flag: "🇨🇲",
        region: "Africa",
        subregion: "Middle Africa",
        example: "671 23 45 67",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "CF",
        alpha3: "CAF",
        numericCode: "140",
        name: "Central African Republic",
        englishName: "Central African Republic",
        dialCode: "+236",
        flag: "🇨🇫",
        region: "Africa",
        subregion: "Middle Africa",
        example: "70 12 34 56",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "TD",
        alpha3: "TCD",
        numericCode: "148",
        name: "Chad",
        englishName: "Chad",
        dialCode: "+235",
        flag: "🇹🇩",
        region: "Africa",
        subregion: "Middle Africa",
        example: "63 01 23 45",
        nationalNumberLength: 8,
        internationalPrefix: "15",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "CG",
        alpha3: "COG",
        numericCode: "178",
        name: "Republic of the Congo",
        englishName: "Republic of the Congo",
        dialCode: "+242",
        flag: "🇨🇬",
        region: "Africa",
        subregion: "Middle Africa",
        example: "06 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "CD",
        alpha3: "COD",
        numericCode: "180",
        name: "Democratic Republic of the Congo",
        englishName: "Democratic Republic of the Congo",
        dialCode: "+243",
        flag: "🇨🇩",
        region: "Africa",
        subregion: "Middle Africa",
        example: "812 345 678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "GQ",
        alpha3: "GNQ",
        numericCode: "226",
        name: "Equatorial Guinea",
        englishName: "Equatorial Guinea",
        dialCode: "+240",
        flag: "🇬🇶",
        region: "Africa",
        subregion: "Middle Africa",
        example: "222 123 456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "GA",
        alpha3: "GAB",
        numericCode: "266",
        name: "Gabon",
        englishName: "Gabon",
        dialCode: "+241",
        flag: "🇬🇦",
        region: "Africa",
        subregion: "Middle Africa",
        example: "06 12 34 56",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "ST",
        alpha3: "STP",
        numericCode: "678",
        name: "São Tomé and Príncipe",
        englishName: "Sao Tome and Principe",
        dialCode: "+239",
        flag: "🇸🇹",
        region: "Africa",
        subregion: "Middle Africa",
        example: "981 2345",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    /* ====================================================================== */
    /* West Africa                                                            */
    /* ====================================================================== */

    {
        code: "BJ",
        alpha3: "BEN",
        numericCode: "204",
        name: "Benin",
        englishName: "Benin",
        dialCode: "+229",
        flag: "🇧🇯",
        region: "Africa",
        subregion: "Western Africa",
        example: "90 12 34 56",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "BF",
        alpha3: "BFA",
        numericCode: "854",
        name: "Burkina Faso",
        englishName: "Burkina Faso",
        dialCode: "+226",
        flag: "🇧🇫",
        region: "Africa",
        subregion: "Western Africa",
        example: "70 12 34 56",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "CV",
        alpha3: "CPV",
        numericCode: "132",
        name: "Cabo Verde",
        englishName: "Cape Verde",
        dialCode: "+238",
        flag: "🇨🇻",
        region: "Africa",
        subregion: "Western Africa",
        example: "991 2345",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "CI",
        alpha3: "CIV",
        numericCode: "384",
        name: "Côte d'Ivoire",
        englishName: "Ivory Coast",
        dialCode: "+225",
        flag: "🇨🇮",
        region: "Africa",
        subregion: "Western Africa",
        example: "07 12 34 56 78",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "GM",
        alpha3: "GMB",
        numericCode: "270",
        name: "Gambia",
        englishName: "The Gambia",
        dialCode: "+220",
        flag: "🇬🇲",
        region: "Africa",
        subregion: "Western Africa",
        example: "301 2345",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "GH",
        alpha3: "GHA",
        numericCode: "288",
        name: "Ghana",
        englishName: "Ghana",
        dialCode: "+233",
        flag: "🇬🇭",
        region: "Africa",
        subregion: "Western Africa",
        example: "24 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "GN",
        alpha3: "GIN",
        numericCode: "324",
        name: "Guinea",
        englishName: "Guinea",
        dialCode: "+224",
        flag: "🇬🇳",
        region: "Africa",
        subregion: "Western Africa",
        example: "620 12 34 56",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "GW",
        alpha3: "GNB",
        numericCode: "624",
        name: "Guinea-Bissau",
        englishName: "Guinea-Bissau",
        dialCode: "+245",
        flag: "🇬🇼",
        region: "Africa",
        subregion: "Western Africa",
        example: "955 123 456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "LR",
        alpha3: "LBR",
        numericCode: "430",
        name: "Liberia",
        englishName: "Liberia",
        dialCode: "+231",
        flag: "🇱🇷",
        region: "Africa",
        subregion: "Western Africa",
        example: "77 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "ML",
        alpha3: "MLI",
        numericCode: "466",
        name: "Mali",
        englishName: "Mali",
        dialCode: "+223",
        flag: "🇲🇱",
        region: "Africa",
        subregion: "Western Africa",
        example: "65 12 34 56",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "MR",
        alpha3: "MRT",
        numericCode: "478",
        name: "Mauritania",
        englishName: "Mauritania",
        dialCode: "+222",
        flag: "🇲🇷",
        region: "Africa",
        subregion: "Western Africa",
        example: "22 34 56 78",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },
    /* ====================================================================== */
    /* Southern Africa                                                        */
    /* ====================================================================== */

    {
        code: "BW",
        alpha3: "BWA",
        numericCode: "072",
        name: "Botswana",
        englishName: "Botswana",
        dialCode: "+267",
        flag: "🇧🇼",
        region: "Africa",
        subregion: "Southern Africa",
        example: "71 123 456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "LS",
        alpha3: "LSO",
        numericCode: "426",
        name: "Lesotho",
        englishName: "Lesotho",
        dialCode: "+266",
        flag: "🇱🇸",
        region: "Africa",
        subregion: "Southern Africa",
        example: "5012 3456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "MW",
        alpha3: "MWI",
        numericCode: "454",
        name: "Malawi",
        englishName: "Malawi",
        dialCode: "+265",
        flag: "🇲🇼",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "991 234 567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "NA",
        alpha3: "NAM",
        numericCode: "516",
        name: "Namibia",
        englishName: "Namibia",
        dialCode: "+264",
        flag: "🇳🇦",
        region: "Africa",
        subregion: "Southern Africa",
        example: "81 234 5678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "SZ",
        alpha3: "SWZ",
        numericCode: "748",
        name: "Eswatini",
        englishName: "Eswatini",
        dialCode: "+268",
        flag: "🇸🇿",
        region: "Africa",
        subregion: "Southern Africa",
        example: "7612 3456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "ZA",
        alpha3: "ZAF",
        numericCode: "710",
        name: "South Africa",
        englishName: "South Africa",
        dialCode: "+27",
        flag: "🇿🇦",
        region: "Africa",
        subregion: "Southern Africa",
        example: "82 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "09",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "ZM",
        alpha3: "ZMB",
        numericCode: "894",
        name: "Zambia",
        englishName: "Zambia",
        dialCode: "+260",
        flag: "🇿🇲",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "955 123 456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "ZW",
        alpha3: "ZWE",
        numericCode: "716",
        name: "Zimbabwe",
        englishName: "Zimbabwe",
        dialCode: "+263",
        flag: "🇿🇼",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "71 234 5678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

];
