/**
 * ============================================================================
 * Ascend Enterprise UI
 * PhoneField
 * ----------------------------------------------------------------------------
 * File: asia.ts
 *
 * Asia country dataset.
 *
 * Part 1
 * - Western Asia
 * - Central Asia
 *
 * ============================================================================
 */

import type {
    PhoneCountry,
} from "../PhoneField.types";

/* -------------------------------------------------------------------------- */
/* Asia                                                                       */
/* -------------------------------------------------------------------------- */

export const ASIAN_COUNTRIES: readonly PhoneCountry[] = [

    /* ====================================================================== */
    /* Western Asia                                                           */
    /* ====================================================================== */

    {
        code: "AM",
        alpha3: "ARM",
        numericCode: "051",
        name: "Armenia",
        englishName: "Armenia",
        dialCode: "+374",
        flag: "🇦🇲",
        region: "Asia",
        subregion: "Western Asia",
        example: "91 123456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "AZ",
        alpha3: "AZE",
        numericCode: "031",
        name: "Azerbaijan",
        englishName: "Azerbaijan",
        dialCode: "+994",
        flag: "🇦🇿",
        region: "Asia",
        subregion: "Western Asia",
        example: "50 123 45 67",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "BH",
        alpha3: "BHR",
        numericCode: "048",
        name: "Bahrain",
        englishName: "Bahrain",
        dialCode: "+973",
        flag: "🇧🇭",
        region: "Asia",
        subregion: "Western Asia",
        example: "3600 1234",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "GE",
        alpha3: "GEO",
        numericCode: "268",
        name: "Georgia",
        englishName: "Georgia",
        dialCode: "+995",
        flag: "🇬🇪",
        region: "Asia",
        subregion: "Western Asia",
        example: "555 123456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "IQ",
        alpha3: "IRQ",
        numericCode: "368",
        name: "Iraq",
        englishName: "Iraq",
        dialCode: "+964",
        flag: "🇮🇶",
        region: "Asia",
        subregion: "Western Asia",
        example: "790 123 4567",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "IL",
        alpha3: "ISR",
        numericCode: "376",
        name: "Israel",
        englishName: "Israel",
        dialCode: "+972",
        flag: "🇮🇱",
        region: "Asia",
        subregion: "Western Asia",
        example: "50 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "JO",
        alpha3: "JOR",
        numericCode: "400",
        name: "Jordan",
        englishName: "Jordan",
        dialCode: "+962",
        flag: "🇯🇴",
        region: "Asia",
        subregion: "Western Asia",
        example: "79 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "KW",
        alpha3: "KWT",
        numericCode: "414",
        name: "Kuwait",
        englishName: "Kuwait",
        dialCode: "+965",
        flag: "🇰🇼",
        region: "Asia",
        subregion: "Western Asia",
        example: "5000 1234",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "LB",
        alpha3: "LBN",
        numericCode: "422",
        name: "Lebanon",
        englishName: "Lebanon",
        dialCode: "+961",
        flag: "🇱🇧",
        region: "Asia",
        subregion: "Western Asia",
        example: "71 123456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "OM",
        alpha3: "OMN",
        numericCode: "512",
        name: "Oman",
        englishName: "Oman",
        dialCode: "+968",
        flag: "🇴🇲",
        region: "Asia",
        subregion: "Western Asia",
        example: "9212 3456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "PS",
        alpha3: "PSE",
        numericCode: "275",
        name: "Palestine",
        englishName: "Palestine",
        dialCode: "+970",
        flag: "🇵🇸",
        region: "Asia",
        subregion: "Western Asia",
        example: "599 123 456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "QA",
        alpha3: "QAT",
        numericCode: "634",
        name: "Qatar",
        englishName: "Qatar",
        dialCode: "+974",
        flag: "🇶🇦",
        region: "Asia",
        subregion: "Western Asia",
        example: "3312 3456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "SA",
        alpha3: "SAU",
        numericCode: "682",
        name: "Saudi Arabia",
        englishName: "Saudi Arabia",
        dialCode: "+966",
        flag: "🇸🇦",
        region: "Asia",
        subregion: "Western Asia",
        example: "50 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "SY",
        alpha3: "SYR",
        numericCode: "760",
        name: "Syria",
        englishName: "Syria",
        dialCode: "+963",
        flag: "🇸🇾",
        region: "Asia",
        subregion: "Western Asia",
        example: "944 567 890",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "TR",
        alpha3: "TUR",
        numericCode: "792",
        name: "Türkiye",
        englishName: "Turkey",
        dialCode: "+90",
        flag: "🇹🇷",
        region: "Asia",
        subregion: "Western Asia",
        example: "532 123 4567",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "AE",
        alpha3: "ARE",
        numericCode: "784",
        name: "United Arab Emirates",
        englishName: "United Arab Emirates",
        dialCode: "+971",
        flag: "🇦🇪",
        region: "Asia",
        subregion: "Western Asia",
        example: "50 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "YE",
        alpha3: "YEM",
        numericCode: "887",
        name: "Yemen",
        englishName: "Yemen",
        dialCode: "+967",
        flag: "🇾🇪",
        region: "Asia",
        subregion: "Western Asia",
        example: "711 234 567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    /* ====================================================================== */
    /* Central Asia                                                           */
    /* ====================================================================== */

    {
        code: "KZ",
        alpha3: "KAZ",
        numericCode: "398",
        name: "Kazakhstan",
        englishName: "Kazakhstan",
        dialCode: "+7",
        flag: "🇰🇿",
        region: "Asia",
        subregion: "Central Asia",
        example: "701 123 4567",
        nationalNumberLength: 10,
        internationalPrefix: "810",
        trunkPrefix: "8",
        independent: true,
    },

    {
        code: "KG",
        alpha3: "KGZ",
        numericCode: "417",
        name: "Kyrgyzstan",
        englishName: "Kyrgyzstan",
        dialCode: "+996",
        flag: "🇰🇬",
        region: "Asia",
        subregion: "Central Asia",
        example: "700 123 456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "TJ",
        alpha3: "TJK",
        numericCode: "762",
        name: "Tajikistan",
        englishName: "Tajikistan",
        dialCode: "+992",
        flag: "🇹🇯",
        region: "Asia",
        subregion: "Central Asia",
        example: "917 12 3456",
        nationalNumberLength: 9,
        internationalPrefix: "810",
        trunkPrefix: "8",
        independent: true,
    },

    {
        code: "TM",
        alpha3: "TKM",
        numericCode: "795",
        name: "Turkmenistan",
        englishName: "Turkmenistan",
        dialCode: "+993",
        flag: "🇹🇲",
        region: "Asia",
        subregion: "Central Asia",
        example: "65 123456",
        nationalNumberLength: 8,
        internationalPrefix: "810",
        trunkPrefix: "8",
        independent: true,
    },

    {
        code: "UZ",
        alpha3: "UZB",
        numericCode: "860",
        name: "Uzbekistan",
        englishName: "Uzbekistan",
        dialCode: "+998",
        flag: "🇺🇿",
        region: "Asia",
        subregion: "Central Asia",
        example: "90 123 45 67",
        nationalNumberLength: 9,
        internationalPrefix: "810",
        trunkPrefix: "8",
        independent: true,
    },
    /* ====================================================================== */
    /* Eastern Asia                                                           */
    /* ====================================================================== */

    {
        code: "CN",
        alpha3: "CHN",
        numericCode: "156",
        name: "China",
        englishName: "China",
        dialCode: "+86",
        flag: "🇨🇳",
        region: "Asia",
        subregion: "Eastern Asia",
        example: "131 2345 6789",
        nationalNumberLength: 11,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "HK",
        alpha3: "HKG",
        numericCode: "344",
        name: "Hong Kong",
        englishName: "Hong Kong",
        dialCode: "+852",
        flag: "🇭🇰",
        region: "Asia",
        subregion: "Eastern Asia",
        example: "5123 4567",
        nationalNumberLength: 8,
        internationalPrefix: "001",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "JP",
        alpha3: "JPN",
        numericCode: "392",
        name: "Japan",
        englishName: "Japan",
        dialCode: "+81",
        flag: "🇯🇵",
        region: "Asia",
        subregion: "Eastern Asia",
        example: "90 1234 5678",
        nationalNumberLength: 10,
        internationalPrefix: "010",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "KP",
        alpha3: "PRK",
        numericCode: "408",
        name: "North Korea",
        englishName: "North Korea",
        dialCode: "+850",
        flag: "🇰🇵",
        region: "Asia",
        subregion: "Eastern Asia",
        example: "191 234 5678",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "KR",
        alpha3: "KOR",
        numericCode: "410",
        name: "South Korea",
        englishName: "South Korea",
        dialCode: "+82",
        flag: "🇰🇷",
        region: "Asia",
        subregion: "Eastern Asia",
        example: "10 1234 5678",
        nationalNumberLength: 10,
        internationalPrefix: "001",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "MN",
        alpha3: "MNG",
        numericCode: "496",
        name: "Mongolia",
        englishName: "Mongolia",
        dialCode: "+976",
        flag: "🇲🇳",
        region: "Asia",
        subregion: "Eastern Asia",
        example: "8811 2233",
        nationalNumberLength: 8,
        internationalPrefix: "001",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "MO",
        alpha3: "MAC",
        numericCode: "446",
        name: "Macao",
        englishName: "Macau",
        dialCode: "+853",
        flag: "🇲🇴",
        region: "Asia",
        subregion: "Eastern Asia",
        example: "6612 3456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "TW",
        alpha3: "TWN",
        numericCode: "158",
        name: "Taiwan",
        englishName: "Taiwan",
        dialCode: "+886",
        flag: "🇹🇼",
        region: "Asia",
        subregion: "Eastern Asia",
        example: "912 345 678",
        nationalNumberLength: 9,
        internationalPrefix: "002",
        trunkPrefix: "0",
        independent: true,
    },

    /* ====================================================================== */
    /* Southern Asia                                                          */
    /* ====================================================================== */

    {
        code: "AF",
        alpha3: "AFG",
        numericCode: "004",
        name: "Afghanistan",
        englishName: "Afghanistan",
        dialCode: "+93",
        flag: "🇦🇫",
        region: "Asia",
        subregion: "Southern Asia",
        example: "70 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "BD",
        alpha3: "BGD",
        numericCode: "050",
        name: "Bangladesh",
        englishName: "Bangladesh",
        dialCode: "+880",
        flag: "🇧🇩",
        region: "Asia",
        subregion: "Southern Asia",
        example: "1712 345678",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "BT",
        alpha3: "BTN",
        numericCode: "064",
        name: "Bhutan",
        englishName: "Bhutan",
        dialCode: "+975",
        flag: "🇧🇹",
        region: "Asia",
        subregion: "Southern Asia",
        example: "17123456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "IN",
        alpha3: "IND",
        numericCode: "356",
        name: "India",
        englishName: "India",
        dialCode: "+91",
        flag: "🇮🇳",
        region: "Asia",
        subregion: "Southern Asia",
        example: "91234 56789",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "IR",
        alpha3: "IRN",
        numericCode: "364",
        name: "Iran",
        englishName: "Iran",
        dialCode: "+98",
        flag: "🇮🇷",
        region: "Asia",
        subregion: "Southern Asia",
        example: "912 345 6789",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "MV",
        alpha3: "MDV",
        numericCode: "462",
        name: "Maldives",
        englishName: "Maldives",
        dialCode: "+960",
        flag: "🇲🇻",
        region: "Asia",
        subregion: "Southern Asia",
        example: "771 2345",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "NP",
        alpha3: "NPL",
        numericCode: "524",
        name: "Nepal",
        englishName: "Nepal",
        dialCode: "+977",
        flag: "🇳🇵",
        region: "Asia",
        subregion: "Southern Asia",
        example: "9841234567",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "PK",
        alpha3: "PAK",
        numericCode: "586",
        name: "Pakistan",
        englishName: "Pakistan",
        dialCode: "+92",
        flag: "🇵🇰",
        region: "Asia",
        subregion: "Southern Asia",
        example: "3001234567",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "LK",
        alpha3: "LKA",
        numericCode: "144",
        name: "Sri Lanka",
        englishName: "Sri Lanka",
        dialCode: "+94",
        flag: "🇱🇰",
        region: "Asia",
        subregion: "Southern Asia",
        example: "712345678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    /* ====================================================================== */
    /* South-Eastern Asia                                                     */
    /* ====================================================================== */

    {
        code: "BN",
        alpha3: "BRN",
        numericCode: "096",
        name: "Brunei",
        englishName: "Brunei",
        dialCode: "+673",
        flag: "🇧🇳",
        region: "Asia",
        subregion: "South-Eastern Asia",
        example: "7123456",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "KH",
        alpha3: "KHM",
        numericCode: "116",
        name: "Cambodia",
        englishName: "Cambodia",
        dialCode: "+855",
        flag: "🇰🇭",
        region: "Asia",
        subregion: "South-Eastern Asia",
        example: "91234567",
        nationalNumberLength: 8,
        internationalPrefix: "001",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "ID",
        alpha3: "IDN",
        numericCode: "360",
        name: "Indonesia",
        englishName: "Indonesia",
        dialCode: "+62",
        flag: "🇮🇩",
        region: "Asia",
        subregion: "South-Eastern Asia",
        example: "81234567890",
        nationalNumberLength: 11,
        internationalPrefix: "001",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "LA",
        alpha3: "LAO",
        numericCode: "418",
        name: "Laos",
        englishName: "Lao People's Democratic Republic",
        dialCode: "+856",
        flag: "🇱🇦",
        region: "Asia",
        subregion: "South-Eastern Asia",
        example: "2023456789",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "MY",
        alpha3: "MYS",
        numericCode: "458",
        name: "Malaysia",
        englishName: "Malaysia",
        dialCode: "+60",
        flag: "🇲🇾",
        region: "Asia",
        subregion: "South-Eastern Asia",
        example: "123456789",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "MM",
        alpha3: "MMR",
        numericCode: "104",
        name: "Myanmar",
        englishName: "Myanmar",
        dialCode: "+95",
        flag: "🇲🇲",
        region: "Asia",
        subregion: "South-Eastern Asia",
        example: "912345678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "PH",
        alpha3: "PHL",
        numericCode: "608",
        name: "Philippines",
        englishName: "Philippines",
        dialCode: "+63",
        flag: "🇵🇭",
        region: "Asia",
        subregion: "South-Eastern Asia",
        example: "9171234567",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "SG",
        alpha3: "SGP",
        numericCode: "702",
        name: "Singapore",
        englishName: "Singapore",
        dialCode: "+65",
        flag: "🇸🇬",
        region: "Asia",
        subregion: "South-Eastern Asia",
        example: "81234567",
        nationalNumberLength: 8,
        internationalPrefix: "001",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "TH",
        alpha3: "THA",
        numericCode: "764",
        name: "Thailand",
        englishName: "Thailand",
        dialCode: "+66",
        flag: "🇹🇭",
        region: "Asia",
        subregion: "South-Eastern Asia",
        example: "812345678",
        nationalNumberLength: 9,
        internationalPrefix: "001",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "TL",
        alpha3: "TLS",
        numericCode: "626",
        name: "Timor-Leste",
        englishName: "Timor-Leste",
        dialCode: "+670",
        flag: "🇹🇱",
        region: "Asia",
        subregion: "South-Eastern Asia",
        example: "77234567",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "VN",
        alpha3: "VNM",
        numericCode: "704",
        name: "Vietnam",
        englishName: "Vietnam",
        dialCode: "+84",
        flag: "🇻🇳",
        region: "Asia",
        subregion: "South-Eastern Asia",
        example: "912345678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

];
