/**
 * ============================================================================
 * Ascend Enterprise UI
 * PhoneField
 * ----------------------------------------------------------------------------
 * File: europe.ts
 *
 * Europe country dataset.
 *
 * Part 1
 * - Northern Europe
 * - Western Europe
 *
 * ============================================================================
 */

import type {
    PhoneCountry,
} from "../PhoneField.types";

/* -------------------------------------------------------------------------- */
/* Europe                                                                     */
/* -------------------------------------------------------------------------- */

export const EUROPEAN_COUNTRIES: readonly PhoneCountry[] = [

    /* ====================================================================== */
    /* Northern Europe                                                        */
    /* ====================================================================== */

    {
        code: "DK",
        alpha3: "DNK",
        numericCode: "208",
        name: "Denmark",
        englishName: "Denmark",
        dialCode: "+45",
        flag: "🇩🇰",
        region: "Europe",
        subregion: "Northern Europe",
        example: "20 12 34 56",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "EE",
        alpha3: "EST",
        numericCode: "233",
        name: "Estonia",
        englishName: "Estonia",
        dialCode: "+372",
        flag: "🇪🇪",
        region: "Europe",
        subregion: "Northern Europe",
        example: "5123 4567",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "FI",
        alpha3: "FIN",
        numericCode: "246",
        name: "Finland",
        englishName: "Finland",
        dialCode: "+358",
        flag: "🇫🇮",
        region: "Europe",
        subregion: "Northern Europe",
        example: "40 1234567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "IS",
        alpha3: "ISL",
        numericCode: "352",
        name: "Iceland",
        englishName: "Iceland",
        dialCode: "+354",
        flag: "🇮🇸",
        region: "Europe",
        subregion: "Northern Europe",
        example: "611 1234",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "IE",
        alpha3: "IRL",
        numericCode: "372",
        name: "Ireland",
        englishName: "Ireland",
        dialCode: "+353",
        flag: "🇮🇪",
        region: "Europe",
        subregion: "Northern Europe",
        example: "85 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "LV",
        alpha3: "LVA",
        numericCode: "428",
        name: "Latvia",
        englishName: "Latvia",
        dialCode: "+371",
        flag: "🇱🇻",
        region: "Europe",
        subregion: "Northern Europe",
        example: "21 234 567",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "LT",
        alpha3: "LTU",
        numericCode: "440",
        name: "Lithuania",
        englishName: "Lithuania",
        dialCode: "+370",
        flag: "🇱🇹",
        region: "Europe",
        subregion: "Northern Europe",
        example: "612 34567",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "8",
        independent: true,
    },

    {
        code: "NO",
        alpha3: "NOR",
        numericCode: "578",
        name: "Norway",
        englishName: "Norway",
        dialCode: "+47",
        flag: "🇳🇴",
        region: "Europe",
        subregion: "Northern Europe",
        example: "412 34 567",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "SE",
        alpha3: "SWE",
        numericCode: "752",
        name: "Sweden",
        englishName: "Sweden",
        dialCode: "+46",
        flag: "🇸🇪",
        region: "Europe",
        subregion: "Northern Europe",
        example: "70 123 45 67",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "GB",
        alpha3: "GBR",
        numericCode: "826",
        name: "United Kingdom",
        englishName: "United Kingdom",
        dialCode: "+44",
        flag: "🇬🇧",
        region: "Europe",
        subregion: "Northern Europe",
        example: "7400 123456",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    /* ====================================================================== */
    /* Western Europe                                                         */
    /* ====================================================================== */

    {
        code: "AT",
        alpha3: "AUT",
        numericCode: "040",
        name: "Austria",
        englishName: "Austria",
        dialCode: "+43",
        flag: "🇦🇹",
        region: "Europe",
        subregion: "Western Europe",
        example: "664 1234567",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "BE",
        alpha3: "BEL",
        numericCode: "056",
        name: "Belgium",
        englishName: "Belgium",
        dialCode: "+32",
        flag: "🇧🇪",
        region: "Europe",
        subregion: "Western Europe",
        example: "470 12 34 56",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "FR",
        alpha3: "FRA",
        numericCode: "250",
        name: "France",
        englishName: "France",
        dialCode: "+33",
        flag: "🇫🇷",
        region: "Europe",
        subregion: "Western Europe",
        example: "6 12 34 56 78",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "DE",
        alpha3: "DEU",
        numericCode: "276",
        name: "Germany",
        englishName: "Germany",
        dialCode: "+49",
        flag: "🇩🇪",
        region: "Europe",
        subregion: "Western Europe",
        example: "1512 3456789",
        nationalNumberLength: 11,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "LI",
        alpha3: "LIE",
        numericCode: "438",
        name: "Liechtenstein",
        englishName: "Liechtenstein",
        dialCode: "+423",
        flag: "🇱🇮",
        region: "Europe",
        subregion: "Western Europe",
        example: "660 123456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "LU",
        alpha3: "LUX",
        numericCode: "442",
        name: "Luxembourg",
        englishName: "Luxembourg",
        dialCode: "+352",
        flag: "🇱🇺",
        region: "Europe",
        subregion: "Western Europe",
        example: "621 123456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "MC",
        alpha3: "MCO",
        numericCode: "492",
        name: "Monaco",
        englishName: "Monaco",
        dialCode: "+377",
        flag: "🇲🇨",
        region: "Europe",
        subregion: "Western Europe",
        example: "6 12 34 56 78",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "NL",
        alpha3: "NLD",
        numericCode: "528",
        name: "Netherlands",
        englishName: "Netherlands",
        dialCode: "+31",
        flag: "🇳🇱",
        region: "Europe",
        subregion: "Western Europe",
        example: "6 12345678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "CH",
        alpha3: "CHE",
        numericCode: "756",
        name: "Switzerland",
        englishName: "Switzerland",
        dialCode: "+41",
        flag: "🇨🇭",
        region: "Europe",
        subregion: "Western Europe",
        example: "79 123 45 67",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },
    /* ====================================================================== */
    /* Southern Europe                                                        */
    /* ====================================================================== */

    {
        code: "AL",
        alpha3: "ALB",
        numericCode: "008",
        name: "Albania",
        englishName: "Albania",
        dialCode: "+355",
        flag: "🇦🇱",
        region: "Europe",
        subregion: "Southern Europe",
        example: "67 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "AD",
        alpha3: "AND",
        numericCode: "020",
        name: "Andorra",
        englishName: "Andorra",
        dialCode: "+376",
        flag: "🇦🇩",
        region: "Europe",
        subregion: "Southern Europe",
        example: "312 345",
        nationalNumberLength: 6,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "BA",
        alpha3: "BIH",
        numericCode: "070",
        name: "Bosnia and Herzegovina",
        englishName: "Bosnia and Herzegovina",
        dialCode: "+387",
        flag: "🇧🇦",
        region: "Europe",
        subregion: "Southern Europe",
        example: "61 123 456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "HR",
        alpha3: "HRV",
        numericCode: "191",
        name: "Croatia",
        englishName: "Croatia",
        dialCode: "+385",
        flag: "🇭🇷",
        region: "Europe",
        subregion: "Southern Europe",
        example: "91 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "CY",
        alpha3: "CYP",
        numericCode: "196",
        name: "Cyprus",
        englishName: "Cyprus",
        dialCode: "+357",
        flag: "🇨🇾",
        region: "Europe",
        subregion: "Southern Europe",
        example: "96 123456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "GI",
        alpha3: "GIB",
        numericCode: "292",
        name: "Gibraltar",
        englishName: "Gibraltar",
        dialCode: "+350",
        flag: "🇬🇮",
        region: "Europe",
        subregion: "Southern Europe",
        example: "54012345",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "GR",
        alpha3: "GRC",
        numericCode: "300",
        name: "Greece",
        englishName: "Greece",
        dialCode: "+30",
        flag: "🇬🇷",
        region: "Europe",
        subregion: "Southern Europe",
        example: "691 123 4567",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "IT",
        alpha3: "ITA",
        numericCode: "380",
        name: "Italy",
        englishName: "Italy",
        dialCode: "+39",
        flag: "🇮🇹",
        region: "Europe",
        subregion: "Southern Europe",
        example: "312 345 6789",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "XK",
        alpha3: "XKX",
        numericCode: "983",
        name: "Kosovo",
        englishName: "Kosovo",
        dialCode: "+383",
        flag: "🇽🇰",
        region: "Europe",
        subregion: "Southern Europe",
        example: "44 123 456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "MT",
        alpha3: "MLT",
        numericCode: "470",
        name: "Malta",
        englishName: "Malta",
        dialCode: "+356",
        flag: "🇲🇹",
        region: "Europe",
        subregion: "Southern Europe",
        example: "9912 3456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "ME",
        alpha3: "MNE",
        numericCode: "499",
        name: "Montenegro",
        englishName: "Montenegro",
        dialCode: "+382",
        flag: "🇲🇪",
        region: "Europe",
        subregion: "Southern Europe",
        example: "67 123 456",
        nationalNumberLength: 8,
        internationalPrefix: "99",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "MK",
        alpha3: "MKD",
        numericCode: "807",
        name: "North Macedonia",
        englishName: "North Macedonia",
        dialCode: "+389",
        flag: "🇲🇰",
        region: "Europe",
        subregion: "Southern Europe",
        example: "70 123 456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "PT",
        alpha3: "PRT",
        numericCode: "620",
        name: "Portugal",
        englishName: "Portugal",
        dialCode: "+351",
        flag: "🇵🇹",
        region: "Europe",
        subregion: "Southern Europe",
        example: "912 345 678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "SM",
        alpha3: "SMR",
        numericCode: "674",
        name: "San Marino",
        englishName: "San Marino",
        dialCode: "+378",
        flag: "🇸🇲",
        region: "Europe",
        subregion: "Southern Europe",
        example: "66 66 12 12",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "RS",
        alpha3: "SRB",
        numericCode: "688",
        name: "Serbia",
        englishName: "Serbia",
        dialCode: "+381",
        flag: "🇷🇸",
        region: "Europe",
        subregion: "Southern Europe",
        example: "60 1234567",
        nationalNumberLength: 9,
        internationalPrefix: "99",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "SI",
        alpha3: "SVN",
        numericCode: "705",
        name: "Slovenia",
        englishName: "Slovenia",
        dialCode: "+386",
        flag: "🇸🇮",
        region: "Europe",
        subregion: "Southern Europe",
        example: "31 234 567",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "ES",
        alpha3: "ESP",
        numericCode: "724",
        name: "Spain",
        englishName: "Spain",
        dialCode: "+34",
        flag: "🇪🇸",
        region: "Europe",
        subregion: "Southern Europe",
        example: "612 345 678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "VA",
        alpha3: "VAT",
        numericCode: "336",
        name: "Vatican City",
        englishName: "Vatican City",
        dialCode: "+379",
        flag: "🇻🇦",
        region: "Europe",
        subregion: "Southern Europe",
        example: "3123456",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },
    /* ====================================================================== */
    /* Eastern Europe                                                         */
    /* ====================================================================== */

    {
        code: "BY",
        alpha3: "BLR",
        numericCode: "112",
        name: "Belarus",
        englishName: "Belarus",
        dialCode: "+375",
        flag: "🇧🇾",
        region: "Europe",
        subregion: "Eastern Europe",
        example: "29 123 45 67",
        nationalNumberLength: 9,
        internationalPrefix: "810",
        trunkPrefix: "8",
        independent: true,
    },

    {
        code: "BG",
        alpha3: "BGR",
        numericCode: "100",
        name: "Bulgaria",
        englishName: "Bulgaria",
        dialCode: "+359",
        flag: "🇧🇬",
        region: "Europe",
        subregion: "Eastern Europe",
        example: "87 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "CZ",
        alpha3: "CZE",
        numericCode: "203",
        name: "Czechia",
        englishName: "Czech Republic",
        dialCode: "+420",
        flag: "🇨🇿",
        region: "Europe",
        subregion: "Eastern Europe",
        example: "601 123 456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "HU",
        alpha3: "HUN",
        numericCode: "348",
        name: "Hungary",
        englishName: "Hungary",
        dialCode: "+36",
        flag: "🇭🇺",
        region: "Europe",
        subregion: "Eastern Europe",
        example: "20 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "06",
        independent: true,
    },

    {
        code: "MD",
        alpha3: "MDA",
        numericCode: "498",
        name: "Moldova",
        englishName: "Moldova",
        dialCode: "+373",
        flag: "🇲🇩",
        region: "Europe",
        subregion: "Eastern Europe",
        example: "621 12 345",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "PL",
        alpha3: "POL",
        numericCode: "616",
        name: "Poland",
        englishName: "Poland",
        dialCode: "+48",
        flag: "🇵🇱",
        region: "Europe",
        subregion: "Eastern Europe",
        example: "512 345 678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "RO",
        alpha3: "ROU",
        numericCode: "642",
        name: "Romania",
        englishName: "Romania",
        dialCode: "+40",
        flag: "🇷🇴",
        region: "Europe",
        subregion: "Eastern Europe",
        example: "712 345 678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "RU",
        alpha3: "RUS",
        numericCode: "643",
        name: "Russia",
        englishName: "Russia",
        dialCode: "+7",
        flag: "🇷🇺",
        region: "Europe",
        subregion: "Eastern Europe",
        example: "912 345 67 89",
        nationalNumberLength: 10,
        internationalPrefix: "810",
        trunkPrefix: "8",
        independent: true,
    },

    {
        code: "SK",
        alpha3: "SVK",
        numericCode: "703",
        name: "Slovakia",
        englishName: "Slovakia",
        dialCode: "+421",
        flag: "🇸🇰",
        region: "Europe",
        subregion: "Eastern Europe",
        example: "901 123 456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "UA",
        alpha3: "UKR",
        numericCode: "804",
        name: "Ukraine",
        englishName: "Ukraine",
        dialCode: "+380",
        flag: "🇺🇦",
        region: "Europe",
        subregion: "Eastern Europe",
        example: "50 123 4567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: true,
    },

];
