/**
 * ============================================================================
 * Ascend Enterprise UI
 * PhoneField
 * ----------------------------------------------------------------------------
 * File: northAmerica.ts
 *
 * North America country dataset.
 *
 * Part 1
 * - North America
 *
 * ============================================================================
 */

import type {
    PhoneCountry,
} from "../PhoneField.types";

/* -------------------------------------------------------------------------- */
/* North America                                                              */
/* -------------------------------------------------------------------------- */

export const NORTH_AMERICAN_COUNTRIES: readonly PhoneCountry[] = [

    {
        code: "AG",
        alpha3: "ATG",
        numericCode: "028",
        name: "Antigua and Barbuda",
        englishName: "Antigua and Barbuda",
        dialCode: "+1-268",
        flag: "🇦🇬",
        region: "North America",
        subregion: "Caribbean",
        example: "268 464 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "BS",
        alpha3: "BHS",
        numericCode: "044",
        name: "Bahamas",
        englishName: "Bahamas",
        dialCode: "+1-242",
        flag: "🇧🇸",
        region: "North America",
        subregion: "Caribbean",
        example: "242 359 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "BB",
        alpha3: "BRB",
        numericCode: "052",
        name: "Barbados",
        englishName: "Barbados",
        dialCode: "+1-246",
        flag: "🇧🇧",
        region: "North America",
        subregion: "Caribbean",
        example: "246 230 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "BZ",
        alpha3: "BLZ",
        numericCode: "084",
        name: "Belize",
        englishName: "Belize",
        dialCode: "+501",
        flag: "🇧🇿",
        region: "North America",
        subregion: "Central America",
        example: "622 1234",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "CA",
        alpha3: "CAN",
        numericCode: "124",
        name: "Canada",
        englishName: "Canada",
        dialCode: "+1",
        flag: "🇨🇦",
        region: "North America",
        subregion: "Northern America",
        example: "416 555 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "1",
        independent: true,
    },

    {
        code: "CR",
        alpha3: "CRI",
        numericCode: "188",
        name: "Costa Rica",
        englishName: "Costa Rica",
        dialCode: "+506",
        flag: "🇨🇷",
        region: "North America",
        subregion: "Central America",
        example: "8312 3456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "CU",
        alpha3: "CUB",
        numericCode: "192",
        name: "Cuba",
        englishName: "Cuba",
        dialCode: "+53",
        flag: "🇨🇺",
        region: "North America",
        subregion: "Caribbean",
        example: "51234567",
        nationalNumberLength: 8,
        internationalPrefix: "119",
        trunkPrefix: "0",
        independent: true,
    },

    {
        code: "DM",
        alpha3: "DMA",
        numericCode: "212",
        name: "Dominica",
        englishName: "Dominica",
        dialCode: "+1-767",
        flag: "🇩🇲",
        region: "North America",
        subregion: "Caribbean",
        example: "767 225 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "DO",
        alpha3: "DOM",
        numericCode: "214",
        name: "Dominican Republic",
        englishName: "Dominican Republic",
        dialCode: "+1-809",
        flag: "🇩🇴",
        region: "North America",
        subregion: "Caribbean",
        example: "809 555 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "1",
        independent: true,
    },

    {
        code: "SV",
        alpha3: "SLV",
        numericCode: "222",
        name: "El Salvador",
        englishName: "El Salvador",
        dialCode: "+503",
        flag: "🇸🇻",
        region: "North America",
        subregion: "Central America",
        example: "7123 4567",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "GD",
        alpha3: "GRD",
        numericCode: "308",
        name: "Grenada",
        englishName: "Grenada",
        dialCode: "+1-473",
        flag: "🇬🇩",
        region: "North America",
        subregion: "Caribbean",
        example: "473 403 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "GT",
        alpha3: "GTM",
        numericCode: "320",
        name: "Guatemala",
        englishName: "Guatemala",
        dialCode: "+502",
        flag: "🇬🇹",
        region: "North America",
        subregion: "Central America",
        example: "5123 4567",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "HT",
        alpha3: "HTI",
        numericCode: "332",
        name: "Haiti",
        englishName: "Haiti",
        dialCode: "+509",
        flag: "🇭🇹",
        region: "North America",
        subregion: "Caribbean",
        example: "3412 3456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "HN",
        alpha3: "HND",
        numericCode: "340",
        name: "Honduras",
        englishName: "Honduras",
        dialCode: "+504",
        flag: "🇭🇳",
        region: "North America",
        subregion: "Central America",
        example: "9123 4567",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "JM",
        alpha3: "JAM",
        numericCode: "388",
        name: "Jamaica",
        englishName: "Jamaica",
        dialCode: "+1-876",
        flag: "🇯🇲",
        region: "North America",
        subregion: "Caribbean",
        example: "876 210 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "MX",
        alpha3: "MEX",
        numericCode: "484",
        name: "Mexico",
        englishName: "Mexico",
        dialCode: "+52",
        flag: "🇲🇽",
        region: "North America",
        subregion: "Central America",
        example: "55 1234 5678",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "NI",
        alpha3: "NIC",
        numericCode: "558",
        name: "Nicaragua",
        englishName: "Nicaragua",
        dialCode: "+505",
        flag: "🇳🇮",
        region: "North America",
        subregion: "Central America",
        example: "8123 4567",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "PA",
        alpha3: "PAN",
        numericCode: "591",
        name: "Panama",
        englishName: "Panama",
        dialCode: "+507",
        flag: "🇵🇦",
        region: "North America",
        subregion: "Central America",
        example: "6123 4567",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: true,
    },
    {
        code: "KN",
        alpha3: "KNA",
        numericCode: "659",
        name: "Saint Kitts and Nevis",
        englishName: "Saint Kitts and Nevis",
        dialCode: "+1-869",
        flag: "🇰🇳",
        region: "North America",
        subregion: "Caribbean",
        example: "869 765 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "LC",
        alpha3: "LCA",
        numericCode: "662",
        name: "Saint Lucia",
        englishName: "Saint Lucia",
        dialCode: "+1-758",
        flag: "🇱🇨",
        region: "North America",
        subregion: "Caribbean",
        example: "758 712 3456",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "VC",
        alpha3: "VCT",
        numericCode: "670",
        name: "Saint Vincent and the Grenadines",
        englishName: "Saint Vincent and the Grenadines",
        dialCode: "+1-784",
        flag: "🇻🇨",
        region: "North America",
        subregion: "Caribbean",
        example: "784 430 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "TT",
        alpha3: "TTO",
        numericCode: "780",
        name: "Trinidad and Tobago",
        englishName: "Trinidad and Tobago",
        dialCode: "+1-868",
        flag: "🇹🇹",
        region: "North America",
        subregion: "Caribbean",
        example: "868 291 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: true,
    },

    {
        code: "US",
        alpha3: "USA",
        numericCode: "840",
        name: "United States",
        englishName: "United States",
        dialCode: "+1",
        flag: "🇺🇸",
        region: "North America",
        subregion: "Northern America",
        example: "202 555 0123",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "1",
        independent: true,
    },

];
