/**
 * ============================================================================
 * Ascend Enterprise UI
 * PhoneField
 * ----------------------------------------------------------------------------
 * File: territories.ts
 *
 * Territories, dependencies and special administrative regions.
 *
 * Part 1
 * - Europe
 *
 * ============================================================================
 */

import type {
    PhoneCountry,
} from "../PhoneField.types";

/* -------------------------------------------------------------------------- */
/* Territories                                                                */
/* -------------------------------------------------------------------------- */

export const TERRITORIES: readonly PhoneCountry[] = [

    /* ====================================================================== */
    /* Europe                                                                 */
    /* ====================================================================== */

    {
        code: "AX",
        alpha3: "ALA",
        numericCode: "248",
        name: "Åland Islands",
        englishName: "Åland Islands",
        dialCode: "+358",
        flag: "🇦🇽",
        region: "Europe",
        subregion: "Northern Europe",
        example: "401234567",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: false,
    },

    {
        code: "FO",
        alpha3: "FRO",
        numericCode: "234",
        name: "Faroe Islands",
        englishName: "Faroe Islands",
        dialCode: "+298",
        flag: "🇫🇴",
        region: "Europe",
        subregion: "Northern Europe",
        example: "211234",
        nationalNumberLength: 6,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "GG",
        alpha3: "GGY",
        numericCode: "831",
        name: "Guernsey",
        englishName: "Guernsey",
        dialCode: "+44",
        flag: "🇬🇬",
        region: "Europe",
        subregion: "Northern Europe",
        example: "7781123456",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: false,
    },

    {
        code: "IM",
        alpha3: "IMN",
        numericCode: "833",
        name: "Isle of Man",
        englishName: "Isle of Man",
        dialCode: "+44",
        flag: "🇮🇲",
        region: "Europe",
        subregion: "Northern Europe",
        example: "7624123456",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: false,
    },

    {
        code: "JE",
        alpha3: "JEY",
        numericCode: "832",
        name: "Jersey",
        englishName: "Jersey",
        dialCode: "+44",
        flag: "🇯🇪",
        region: "Europe",
        subregion: "Northern Europe",
        example: "7797123456",
        nationalNumberLength: 10,
        internationalPrefix: "00",
        trunkPrefix: "0",
        independent: false,
    },

    {
        code: "SJ",
        alpha3: "SJM",
        numericCode: "744",
        name: "Svalbard and Jan Mayen",
        englishName: "Svalbard and Jan Mayen",
        dialCode: "+47",
        flag: "🇸🇯",
        region: "Europe",
        subregion: "Northern Europe",
        example: "41234567",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    /* ====================================================================== */
    /* Asia                                                                   */
    /* ====================================================================== */

    {
        code: "HK",
        alpha3: "HKG",
        numericCode: "344",
        name: "Hong Kong",
        englishName: "Hong Kong",
        dialCode: "+852",
        flag: "🇭🇰",
        region: "Asia",
        subregion: "Eastern Asia",
        example: "51234567",
        nationalNumberLength: 8,
        internationalPrefix: "001",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "MO",
        alpha3: "MAC",
        numericCode: "446",
        name: "Macao",
        englishName: "Macau",
        dialCode: "+853",
        flag: "🇲🇴",
        region: "Asia",
        subregion: "Eastern Asia",
        example: "66123456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    /* ====================================================================== */
    /* North America & Caribbean                                              */
    /* ====================================================================== */

    {
        code: "AI",
        alpha3: "AIA",
        numericCode: "660",
        name: "Anguilla",
        englishName: "Anguilla",
        dialCode: "+1-264",
        flag: "🇦🇮",
        region: "North America",
        subregion: "Caribbean",
        example: "264 235 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "AW",
        alpha3: "ABW",
        numericCode: "533",
        name: "Aruba",
        englishName: "Aruba",
        dialCode: "+297",
        flag: "🇦🇼",
        region: "North America",
        subregion: "Caribbean",
        example: "5601234",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },
    {
        numericCode: "060",
        flag: "🇧🇲",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: false,
    },
    {
        code: "BQ",
        alpha3: "BES",
        numericCode: "535",
        name: "Caribbean Netherlands",
        dialCode: "+599",
        flag: "🇧🇶",
        region: "North America",
        subregion: "Caribbean",
        example: "3181234",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "KY",
        alpha3: "CYM",
        numericCode: "136",
        name: "Cayman Islands",
        englishName: "Cayman Islands",
        dialCode: "+1-345",
        flag: "🇰🇾",
        region: "North America",
        subregion: "Caribbean",
        example: "345 916 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "CW",
        alpha3: "CUW",
        numericCode: "531",
        name: "Curaçao",
        englishName: "Curaçao",
        dialCode: "+599",
        flag: "🇨🇼",
        region: "North America",
        subregion: "Caribbean",
        example: "9511234",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "GL",
        alpha3: "GRL",
        numericCode: "304",
        name: "Greenland",
        englishName: "Greenland",
        dialCode: "+299",
        flag: "🇬🇱",
        region: "North America",
        subregion: "Northern America",
        example: "221234",
        nationalNumberLength: 6,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "GP",
        alpha3: "GLP",
        numericCode: "312",
        name: "Guadeloupe",
        englishName: "Guadeloupe",
        dialCode: "+590",
        flag: "🇬🇵",
        region: "North America",
        subregion: "Caribbean",
        example: "690123456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "MQ",
        alpha3: "MTQ",
        numericCode: "474",
        name: "Martinique",
        englishName: "Martinique",
        dialCode: "+596",
        flag: "🇲🇶",
        region: "North America",
        subregion: "Caribbean",
        example: "696123456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "MS",
        alpha3: "MSR",
        numericCode: "500",
        name: "Montserrat",
        englishName: "Montserrat",
        dialCode: "+1-664",
        flag: "🇲🇸",
        region: "North America",
        subregion: "Caribbean",
        example: "664 492 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "PR",
        alpha3: "PRI",
        numericCode: "630",
        name: "Puerto Rico",
        englishName: "Puerto Rico",
        dialCode: "+1",
        flag: "🇵🇷",
        region: "North America",
        subregion: "Caribbean",
        example: "787 555 1234",
        englishName: "Bonaire, Sint Eustatius and Saba",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "1",

        independent: false,
    },
        example: "441 234 1234",

    {
        code: "BL",
        alpha3: "BLM",
        numericCode: "652",
        subregion: "Northern America",
        name: "Saint Barthélemy",
        englishName: "Saint Barthélemy",
        dialCode: "+590",
        region: "North America",
        flag: "🇧🇱",
        englishName: "Bermuda",
        region: "North America",
        subregion: "Caribbean",
        example: "690123456",
        nationalNumberLength: 9,
        dialCode: "+1-441",
        internationalPrefix: "00",
        name: "Bermuda",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "MF",
        alpha3: "BMU",
        alpha3: "MAF",
        numericCode: "663",
        name: "Saint Martin",
        englishName: "Saint Martin (French part)",
        code: "BM",
        dialCode: "+590",
        flag: "🇲🇫",
        region: "North America",
        subregion: "Caribbean",
        example: "690123456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },


    {
        code: "SX",
        alpha3: "SXM",
        numericCode: "534",
        name: "Sint Maarten",
        englishName: "Sint Maarten (Dutch part)",
        dialCode: "+1-721",
        flag: "🇸🇽",
        region: "North America",
        subregion: "Caribbean",
        example: "721 520 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: false,

    },

    {
        code: "TC",
        alpha3: "TCA",
        numericCode: "796",
        name: "Turks and Caicos Islands",
        englishName: "Turks and Caicos Islands",
        dialCode: "+1-649",
        flag: "🇹🇨",
        region: "North America",
        subregion: "Caribbean",
        example: "649 231 1234",
        nationalNumberLength: 10,

        internationalPrefix: "011",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "VG",
        alpha3: "VGB",
        numericCode: "092",
        name: "British Virgin Islands",
        englishName: "British Virgin Islands",
        dialCode: "+1-284",
        flag: "🇻🇬",
        region: "North America",
        subregion: "Caribbean",
        example: "284 499 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "VI",
        alpha3: "VIR",
        numericCode: "850",
        name: "U.S. Virgin Islands",
        englishName: "United States Virgin Islands",
        dialCode: "+1-340",
        flag: "🇻🇮",
        region: "North America",
        subregion: "Caribbean",
        example: "340 774 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: false,
    },

    /* ====================================================================== */
    /* Oceania                                                                */
    /* ====================================================================== */

    {
        code: "AS",
        alpha3: "ASM",
        numericCode: "016",
        name: "American Samoa",
        englishName: "American Samoa",
        dialCode: "+1-684",
        flag: "🇦🇸",
        region: "Oceania",
        subregion: "Polynesia",
        example: "684 733 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "CK",
        alpha3: "COK",
        numericCode: "184",
        name: "Cook Islands",
        englishName: "Cook Islands",
        dialCode: "+682",
        flag: "🇨🇰",
        region: "Oceania",
        subregion: "Polynesia",
        example: "71234",
        nationalNumberLength: 5,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "GU",
        alpha3: "GUM",
        numericCode: "316",
        name: "Guam",
        englishName: "Guam",
        dialCode: "+1-671",
        flag: "🇬🇺",
        region: "Oceania",
        subregion: "Micronesia",
        example: "671 688 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "NC",
        alpha3: "NCL",
        numericCode: "540",
        name: "New Caledonia",
        englishName: "New Caledonia",
        dialCode: "+687",
        flag: "🇳🇨",
        region: "Oceania",
        subregion: "Melanesia",
        example: "751234",
        nationalNumberLength: 6,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "NF",
        alpha3: "NFK",
        numericCode: "574",
        name: "Norfolk Island",
        englishName: "Norfolk Island",
        dialCode: "+672",
        flag: "🇳🇫",
        region: "Oceania",
        subregion: "Australia and New Zealand",
        example: "381234",
        nationalNumberLength: 6,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "NU",
        alpha3: "NIU",
        numericCode: "570",
        name: "Niue",
        englishName: "Niue",
        dialCode: "+683",
        flag: "🇳🇺",
        region: "Oceania",
        subregion: "Polynesia",
        example: "4012",
        nationalNumberLength: 4,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "MP",
        alpha3: "MNP",
        numericCode: "580",
        name: "Northern Mariana Islands",
        englishName: "Northern Mariana Islands",
        dialCode: "+1-670",
        flag: "🇲🇵",
        region: "Oceania",
        subregion: "Micronesia",
        example: "670 234 1234",
        nationalNumberLength: 10,
        internationalPrefix: "011",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "PF",
        alpha3: "PYF",
        numericCode: "258",
        name: "French Polynesia",
        englishName: "French Polynesia",
        dialCode: "+689",
        flag: "🇵🇫",
        region: "Oceania",
        subregion: "Polynesia",
        example: "87123456",
        nationalNumberLength: 8,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "PN",
        alpha3: "PCN",
        numericCode: "612",
        name: "Pitcairn Islands",
        englishName: "Pitcairn Islands",
        dialCode: "+64",
        flag: "🇵🇳",
        region: "Oceania",
        subregion: "Polynesia",
        example: "912345678",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "TK",
        alpha3: "TKL",
        numericCode: "772",
        name: "Tokelau",
        englishName: "Tokelau",
        dialCode: "+690",
        flag: "🇹🇰",
        region: "Oceania",
        subregion: "Polynesia",
        example: "2010",
        nationalNumberLength: 4,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "WF",
        alpha3: "WLF",
        numericCode: "876",
        name: "Wallis and Futuna",
        englishName: "Wallis and Futuna",
        dialCode: "+681",
        flag: "🇼🇫",
        region: "Oceania",
        subregion: "Polynesia",
        example: "501234",
        nationalNumberLength: 6,
        internationalPrefix: "19",
        trunkPrefix: "",
        independent: false,
    },
    /* ====================================================================== */
    /* South America                                                          */
    /* ====================================================================== */

    {
        code: "FK",
        alpha3: "FLK",
        numericCode: "238",
        name: "Falkland Islands",
        englishName: "Falkland Islands (Malvinas)",
        dialCode: "+500",
        flag: "🇫🇰",
        region: "South America",
        subregion: "South America",
        example: "51234",
        nationalNumberLength: 5,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "GS",
        alpha3: "SGS",
        numericCode: "239",
        name: "South Georgia and the South Sandwich Islands",
        englishName: "South Georgia and the South Sandwich Islands",
        dialCode: "+500",
        flag: "🇬🇸",
        region: "South America",
        subregion: "South America",
        example: "51234",
        nationalNumberLength: 5,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    /* ====================================================================== */
    /* Africa / Indian Ocean                                                  */
    /* ====================================================================== */

    {
        code: "IO",
        alpha3: "IOT",
        numericCode: "086",
        name: "British Indian Ocean Territory",
        englishName: "British Indian Ocean Territory",
        dialCode: "+246",
        flag: "🇮🇴",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "3701234",
        nationalNumberLength: 7,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "YT",
        alpha3: "MYT",
        numericCode: "175",
        name: "Mayotte",
        englishName: "Mayotte",
        dialCode: "+262",
        flag: "🇾🇹",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "639123456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    {
        code: "RE",
        alpha3: "REU",
        numericCode: "638",
        name: "Réunion",
        englishName: "Réunion",
        dialCode: "+262",
        flag: "🇷🇪",
        region: "Africa",
        subregion: "Eastern Africa",
        example: "692123456",
        nationalNumberLength: 9,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

    /* ====================================================================== */
    /* Atlantic                                                               */
    /* ====================================================================== */

    {
        code: "SH",
        alpha3: "SHN",
        numericCode: "654",
        name: "Saint Helena",
        englishName: "Saint Helena, Ascension and Tristan da Cunha",
        dialCode: "+290",
        flag: "🇸🇭",
        region: "Africa",
        subregion: "Western Africa",
        example: "51234",
        nationalNumberLength: 5,
        internationalPrefix: "00",
        trunkPrefix: "",
        independent: false,
    },

];
